spring:
  application:
    name: coupons
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      db-type: postgresql
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/coupons
      username: postgres
      password: 123456
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml